baseURL: https://cuso4.me/
languageCode: en-us
title: '[[logs]]'
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsCodefences: true
# pygmentsUseClasses: true


markup:
  highlight:
    # anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    # noClasses: false
    noHl: false
    style: doom-one
    tabWidth: 4


menu:
  main:
    - name: Home
      url: /
      weight: 10
    - name: About
      url: /about
      weight: 20
    - name: Posts
      url: /posts
      weight: 25
    - name: "🍞"
      url: /bread
      weight: 100

outputs:
    home:
        - HTML
        - RSS
        - JSON


params:
  assets:
    disableHLJS: true

  env: production
  author: Shuntian Liu
  math: true

  defaultTheme: auto

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true
  ShowToc: true
  profileMode:
    enabled: true
    title: "A website" # optional default will be site title
    subtitle: "and its subtitle"
    # imageUrl: "<image link>" # optional
    # imageTitle: "<title of image as alt>" # optional
    # imageWidth: 120 # custom size
    # imageHeight: 120 # custom size
    buttons:
      - name: Blog
        url: "/posts"
    #   - name: Github
    #     url: "https://github.com/"

  socialIcons:
    - name: twitter
      title: twitter
      url: 'https://twitter.com/Incipit0'
    - name: email
      url: 'mailto:shuntian.liu@outlook.com'
    - name: github
      url: 'https://github.com/Vincent-lau'
    - name: telegram
      url: 'https://t.me/lst_vincent'
    - name: linkedin
      url: 'https://www.linkedin.com/in/shuntian-liu/'
    - name: cv
      url: '/cv.pdf'
    - name: bilibili
      url: 'https://space.bilibili.com/94629035?spm_id_from=333.1007.0.0'
