baseURL = 'https://cuso4.me/'
languageCode = 'en-us'
title = '[[logs]]'
theme = "PaperMod"

# sectionPagesMenu = "main"

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 20
[[menu.main]]
  name = 'Posts'
  url = '/posts'
  weight = 25
[[menu.main]]
  name = 'Contact'
  url = '/contact'
  weight = 30
[params]
  favicon=true